TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv6k
TARGET_CPU_VARIANT := arm11
TARGET_CPU_ABI := armeabi

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false

# Set up the local kernel.
TARGET_KERNEL_ARCH := $(TARGET_ARCH)
TARGET_KERNEL_SRC := hardware/bsp/kernel/rpi
TARGET_KERNEL_DEFCONFIG := bcmrpi_defconfig
TARGET_KERNEL_CONFIGS := $(PWD)/device/brcm/rpi/soc/soc.kconf
TARGET_KERNEL_DTB := bcm2708-rpi-b-plus.dtb
TARGET_KERNEL_DTB_APPEND := false

TARGET_SKIP_OTA_PACKAGE := true

TARGET_BOARD_INFO_FILE := device/brcm/rpi/board-info.txt

TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
TARGET_USERIMAGES_USE_EXT4 := true

BOARD_SYSTEMIMAGE_PARTITION_SIZE := 536870912 # 512M
BOARD_CACHEIMAGE_PARTITION_SIZE := 134217728 # 128M
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_PARTITION_SIZE := 134217728 # 128M

BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_MALLOC_ALIGNMENT := 16

BOARD_SEPOLICY_DIRS += device/brcm/rpi/sepolicy

TARGET_BOARD_PLATFORM := bcm2708

# Must be defined at the end of the file
$(call add_device_packages)
